export const dailyVersesESV: string[] = [
  "John 3:16 — “For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.”",
  "Psalm 23:1 — “The Lord is my shepherd; I shall not want.”",
  "Philippians 4:13 — “I can do all things through him who strengthens me.”",
  "Proverbs 3:5–6 — “Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.”",
  "Romans 8:28 — “And we know that for those who love God all things work together for good, for those who are called according to his purpose.”",
  "Jeremiah 29:11 — “For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope.”",
  "Isaiah 41:10 — “Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.”",
  "Matthew 11:28 — “Come to me, all who labor and are heavy laden, and I will give you rest.”",
  "Romans 12:2 — “Do not be conformed to this world, but be transformed by the renewal of your mind...”",
  "Psalm 119:105 — “Your word is a lamp to my feet and a light to my path.”",
  "1 Corinthians 13:4 — “Love is patient and kind; love does not envy or boast; it is not arrogant.”",
  "James 1:5 — “If any of you lacks wisdom, let him ask God…”",
  "Psalm 46:1 — “God is our refuge and strength, a very present help in trouble.”",
  "Hebrews 11:1 — “Now faith is the assurance of things hoped for, the conviction of things not seen.”",
  "Romans 5:8 — “But God shows his love for us in that while we were still sinners, Christ died for us.”",
  "1 Thessalonians 5:16–18 — “Rejoice always, pray without ceasing, give thanks in all circumstances…”",
  "Matthew 6:33 — “But seek first the kingdom of God and his righteousness, and all these things will be added to you.”",
  "2 Corinthians 5:17 — “Therefore, if anyone is in Christ, he is a new creation…”",
  "Psalm 55:22 — “Cast your burden on the Lord, and he will sustain you…”",
  "Ephesians 2:8–9 — “For by grace you have been saved through faith…”",
  "Romans 6:23 — “For the wages of sin is death, but the free gift of God is eternal life…”",
  "Mark 12:30 — “And you shall love the Lord your God with all your heart…”",
  "Galatians 5:22–23 — “But the fruit of the Spirit is love, joy, peace…”",
  "John 14:6 — “Jesus said to him, ‘I am the way, and the truth, and the life…”",
  "Psalm 37:4 — “Delight yourself in the Lord, and he will give you the desires of your heart.”",
  "John 1:1 — “In the beginning was the Word, and the Word was with God, and the Word was God.”",
  "Romans 10:9 — “If you confess with your mouth that Jesus is Lord and believe in your heart…”",
  "Colossians 3:23 — “Whatever you do, work heartily, as for the Lord and not for men…”",
  "Psalm 34:8 — “Oh, taste and see that the Lord is good! Blessed is the man who takes refuge in him!”",
  "Joshua 1:9 — “Be strong and courageous. Do not be frightened, and do not be dismayed…”"
];
